from __future__ import annotations

# Central list of component ids used across the Dash app.
FETCH_PANEL_TOGGLE_BUTTON = "fetch-panel-toggle-button"
FETCH_PANEL_CONTAINER = "fetch-panel-container"
FORMAT_PANEL_TOGGLE_BUTTON = "format-panel-toggle-button"
FORMAT_PANEL_CONTAINER = "format-panel-container"
CHART_CONTAINER = "chart-container"
CHART_SERIES_STORE = "chart-series-store"
COMBINED_DATA_STORE = "combined-data-store"
FETCH_MODE_RADIO = "fetch-mode-radio"
TICKER_INPUT = "ticker-input"
START_DATE_INPUT = "start-date-input"
END_DATE_INPUT = "end-date-input"
PERIODICITY_DROPDOWN = "periodicity-dropdown"
FIELD_GROUP_INPUT = "field-group-input"
TRANSFORM_TOGGLE = "transform-toggle"
TRANSFORM_MONTHS = "transform-months"
TRANSFORM_TYPE = "transform-type"
TRANSFORM_ALIGN = "transform-align"
FETCH_BUTTON = "fetch-button"
MESSAGE_CONTAINER = "message-container"
CHART_TITLE_INPUT = "chart-title-input"
X_LABEL_INPUT = "x-label-input"
Y_LABEL_INPUT = "y-label-input"
SERIES_RIGHT_AXIS_DROPDOWN = "series-right-axis-dropdown"
SERIES_REMOVE_DROPDOWN = "series-remove-dropdown"
REMOVE_SERIES_BUTTON = "remove-series-button"
CLEAR_ALL_BUTTON = "clear-all-button"
SERIES_SUMMARY = "series-summary"
TIME_SERIES_CHART = "time-series-chart"
CHART_STATUS = "chart-status"


